import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Download, FileText } from "lucide-react";
import { useCurrency } from "@/hooks/useCurrency";
import jsPDF from 'jspdf';

interface InvoiceDetailDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  invoice: any;
}

export function InvoiceDetailDialog({ open, onOpenChange, invoice }: InvoiceDetailDialogProps) {
  const { formatCurrency } = useCurrency();

  if (!invoice) return null;

  const getStatusColor = (status: string) => {
    const colors: Record<string, string> = {
      draft: "bg-gray-100 text-gray-800",
      sent: "bg-blue-100 text-blue-800",
      paid: "bg-green-100 text-green-800",
      overdue: "bg-red-100 text-red-800",
      cancelled: "bg-gray-100 text-gray-800",
      on_hold: "bg-orange-100 text-orange-800",
    };
    return colors[status] || colors.draft;
  };

  const handleDownload = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.text('INVOICE', 105, 20, { align: 'center' });
    
    // Invoice details
    doc.setFontSize(12);
    doc.text(`Invoice Number: ${invoice.invoice_number || 'Draft'}`, 20, 40);
    doc.text(`Date: ${new Date(invoice.created_at).toLocaleDateString()}`, 20, 50);
    doc.text(`Status: ${invoice.status?.toUpperCase()}`, 20, 60);
    
    // Divider
    doc.line(20, 70, 190, 70);
    
    // Work order details
    doc.text(`Work Order: ${invoice.work_orders?.wo_number || 'N/A'}`, 20, 80);
    
    if (invoice.hold_reason) {
      doc.setFontSize(10);
      doc.setTextColor(255, 100, 0);
      doc.text(`Hold Reason: ${invoice.hold_reason}`, 20, 90);
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);
    }
    
    // Divider
    doc.line(20, 100, 190, 100);
    
    // Financial details
    doc.text(`Subtotal: ${formatCurrency(Number(invoice.subtotal))}`, 20, 110);
    
    if (invoice.penalties && Number(invoice.penalties) > 0) {
      doc.setTextColor(255, 0, 0);
      doc.text(`Penalties: -${formatCurrency(Number(invoice.penalties))}`, 20, 120);
      doc.setTextColor(0, 0, 0);
    }
    
    // Total
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text(`Total: ${formatCurrency(Number(invoice.total_amount))}`, 20, invoice.penalties ? 135 : 125);
    
    // Footer
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text('Generated by Guardian Flow Field Service Platform', 105, 280, { align: 'center' });
    
    // Save
    doc.save(`${invoice.invoice_number || 'invoice'}.pdf`);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Invoice Details
          </DialogTitle>
          <DialogDescription>
            Complete invoice breakdown and payment information
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          <div className="flex items-start justify-between">
            <div>
              <h3 className="text-2xl font-bold">{invoice.invoice_number || 'Draft Invoice'}</h3>
              <p className="text-sm text-muted-foreground mt-1">
                Created: {new Date(invoice.created_at).toLocaleDateString()}
              </p>
            </div>
            <Badge className={getStatusColor(invoice.status)}>{invoice.status}</Badge>
          </div>

          <Separator />

          <div className="grid gap-4">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">Work Order:</span>
              <span className="font-medium">{invoice.work_orders?.wo_number || 'N/A'}</span>
            </div>
            
            {invoice.hold_reason && (
              <div className="p-3 bg-orange-50 border border-orange-200 rounded-md">
                <p className="text-sm font-medium text-orange-800">Hold Reason:</p>
                <p className="text-sm text-orange-700">{invoice.hold_reason}</p>
              </div>
            )}
          </div>

          <Separator />

          <div className="space-y-3">
            <h4 className="font-semibold">Invoice Breakdown</h4>
            
            <div className="space-y-2">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Subtotal</span>
                <span className="font-medium">{formatCurrency(Number(invoice.subtotal))}</span>
              </div>

              {invoice.penalties && Number(invoice.penalties) > 0 && (
                <div className="flex justify-between text-red-600">
                  <span>Penalties Applied</span>
                  <span className="font-medium">-{formatCurrency(Number(invoice.penalties))}</span>
                </div>
              )}

              <Separator />

              <div className="flex justify-between text-lg font-bold">
                <span>Total Amount</span>
                <span>{formatCurrency(Number(invoice.total_amount))}</span>
              </div>
            </div>
          </div>

          <Separator />

          <div className="flex gap-2">
            <Button onClick={handleDownload} className="flex-1">
              <Download className="h-4 w-4 mr-2" />
              Download Invoice
            </Button>
            <Button variant="outline" onClick={() => onOpenChange(false)}>
              Close
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
